apiVersion: v1
kind: Service

metadata:
  name: smart-water-rl-service

spec:
  selector:
    app: smart-water-rl

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer